### ISSUE TITLE
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4.

### ISSUE THREAD

**Issue by zxiol** [NiFangBaAGe/Explicit-Visual-Prompt#1]
Hello, congratulations. Why do packages downloaded according to requirements report errors? Can you help me solve it? Moreover, directly following the instruction {pip install - r requirements. txt} will also result in an error. I really hope you can help me.

Traceback (most recent call last):
  File "train.py", line 13, in <module>
    import models
  File "/mnt/cephfs/home/alvin/xionglin/Explicit-Visual-Prompt/models/__init__.py", line 2, in <module>
    from . import segformer, setr
  File "/mnt/cephfs/home/alvin/xionglin/Explicit-Visual-Prompt/models/segformer.py", line 12, in <module>
    from .mmseg.models import build_segmentor
  File "/mnt/cephfs/home/alvin/xionglin/Explicit-Visual-Prompt/models/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/mnt/cephfs/home/alvin/xionglin/Explicit-Visual-Prompt/models/mmseg/models/backbones/__init__.py", line 1, in <module>
    from .cgnet import CGNet
  File "/mnt/cephfs/home/alvin/xionglin/Explicit-Visual-Prompt/models/mmseg/models/backbones/cgnet.py", line 10, in <module>
    from ...utils import get_root_logger
  File "/mnt/cephfs/home/alvin/xionglin/Explicit-Visual-Prompt/models/mmseg/utils/__init__.py", line 1, in <module>
    from .collect_env import collect_env
  File "/mnt/cephfs/home/alvin/xionglin/Explicit-Visual-Prompt/models/mmseg/utils/collect_env.py", line 4, in <module>
    import mmseg
  File "/mnt/cephfs/home/alvin/anaconda3/envs/vpt/lib/python3.6/site-packages/mmseg/__init__.py", line 62, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4.
![image](https://user-images.githubusercontent.com/125778426/235205068-1d162ab5-4926-477d-b2ac-2d135cabe183.png)

![image](https://user-images.githubusercontent.com/125778426/235205003-c190a23e-c897-4bc1-b662-dc5af82129b1.png)

**Comment by 85zhanghao** [comment]
I encountered the same problem as you, did you solve the problem?

**Comment by NiFangBaAGe** [comment]
Thank you for your interest in our work.
This seems to be an incompatibility between package versions.
Please try the following packages:
torch1.4.0+cu92, mmcv-full1.3.0

**Comment by 85zhanghao** [comment]
Thanks for your reply about this issue, but according to the packages: torch1.4.0+cu92, mmcv-full1.3.0, the error still occurs. 
I'm wondering if there are incompatibilities between other package versions in requirements.txt? 

    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc4.
